version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: web
    ports:
      - '5173:5173'
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'exam_system'
      MYSQL_ROOT_PASSWORD: 123456
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    ports:
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
      - '3004:3004'
    depends_on:
      - mysql
      - redis
